version: "3.8"

services:
  whoami:
    image: docker.io/traefik/whoami
    container_name: whoami-app
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.bangasser.dev`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.middlewares.pass-cert.passtlsclientcert.pem=true"
      - "traefik.http.routers.whoami.middlewares=pass-cert"
      - "traefik.http.middlewares.pass-cert.passtlsclientcert.info.subject.commonname=true"
      - "traefik.http.routers.whoami.tls.options=require-mtls@file"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.bangasser.dev`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.tls.options=require-mtls@file"

  step-ca-init:
    image: docker.io/smallstep/step-ca
    user: "0:0"
    environment:
      CA_PASSWORD: ${REMOTE_DB_PASSWORD}
      DB_HOST: "na-bangasser-db-0-bangasser-db.g.aivencloud.com"
    volumes:
      - ca:/home/step:Z
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if [ ! -f /home/step/config/ca.json ]; then
          echo "Initializing CA from cold start..."
          apk add -q jq
          
          echo -n "$$CA_PASSWORD" > /tmp/pass.txt
          
          step ca init --name='Bangasser CA' \
            --dns='ca.bangasser.dev,localhost,ca' \
            --address=':9000' \
            --provisioner='admin@bangasser.dev' \
            --password-file=/tmp/pass.txt \
            --provisioner-password-file=/tmp/pass.txt \
            --no-db

          step ca provisioner add acme --type ACME --ca-config /home/step/config/ca.json

          mv /tmp/pass.txt /home/step/secrets/password

          jq --arg db_host "$$DB_HOST" '.db = {
            "type": "postgresql",
            "database": "stepca",
            "dataSource": ("host=" + $$db_host + " port=27936 user=stepca_dbuser sslmode=require")
          }' /home/step/config/ca.json > /tmp/ca.json
          
          cat /tmp/ca.json > /home/step/config/ca.json
          
          chown -R 1000:1000 /home/step
          
          rm /tmp/ca.json
          echo "Initialization complete."
        else
          echo "CA already initialized. Skipping cold start."
        fi

  ca:
    image: docker.io/smallstep/step-ca
    environment:
      PGPASSWORD: ${REMOTE_DB_PASSWORD}
    ports:
      - "9000:9000"
    depends_on:
      step-ca-init:
        condition: service_completed_successfully
    restart: unless-stopped
    volumes:
      - ca:/home/step:Z
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.step-router.rule=HostSNI(`ca.bangasser.dev`)"
      - "traefik.tcp.routers.step-router.entrypoints=websecure"
      - "traefik.tcp.routers.step-router.tls.passthrough=true"
      - "traefik.tcp.routers.step-router.service=step-svc"
      - "traefik.tcp.services.step-svc.loadbalancer.server.port=9000"

volumes:
  ca: {}

networks:
  proxy:
    external: true
    name: proxy
